### ISSUE TITLE
The notebook doesnt start to train

### ISSUE THREAD

**Issue by pendex900x** [airxiechao/simple-car-plate-recognition-2#1]
Which version do you use?

At least doesnt work in google colab.

https://prnt.sc/sft1ni

**Comment by airxiechao** [comment]
have you generated the training images?

**Comment by pendex900x** [comment]
When I try to generate the trained images it appears this https://prnt.sc/sfv8v7

**Comment by airxiechao** [comment]
import os
os.chdir('... dir of generateCarPlate ...')
!python genCarPlate.py 100

**Comment by pendex900x** [comment]
Thanks very much! it is working 👍 , Do you have any paper or something similar so that I can study this?
